### ISSUE TITLE
use the new logo for the favicon. 

### ISSUE THREAD

**Issue by kohlhase** [OpenDreamKit/OpenDreamKit.github.io#23]
it is currently a funny white H on black square.

**Comment by slel** [comment]
Possibly that H was for Horizon2020?
+1 to new favicon

**Comment by embray** [comment]
imagemagick can be used to easily convert an svg to a .ico file encapuslating different sized icons.  For example:

```
convert odk-logo.svg -define icon:auto-resize="256,128,96,48,32,16" favicon.ico
```

**Comment by defeo** [comment]
Done, please test.

**Comment by kohlhase** [comment]
works for me, thanks to all!
