### ISSUE TITLE
Choose a pre-made theme

### ISSUE THREAD

**Issue by defeo** [OpenDreamKit/OpenDreamKit.github.io#3]
To get the website started rapidly and effortlessly, it is best to pick-up a ready-made theme for Jekyll.

Here's some good ones :
- Lanyon https://github.com/poole/lanyon,
- Hyde https://github.com/poole/hyde,
- Fork 'n go (many themes) http://jlord.us/forkngo/,
- Jekyll themes http://jekyllthemes.org/

I personally like [Poole](http://getpoole.com/), upon which [Lanyon](http://lanyon.getpoole.com/) and [Hyde](http://hyde.getpoole.com/) are based (check out http://idealcodes.github.io/clic-2014/), because it is very minimal and customizable. [Feeling responsive](http://phlow.github.io/feeling-responsive/) is a nice richer theme.

...or we could use a startup generator http://tiffzhang.com/startup/ :smile:

**Comment by nthiery** [comment]
Sounds good to me. I have no specific preference between the themes.
Do you mind doing the basic setup?

**Comment by defeo** [comment]
Sure I can do it.

Let's leave this issue open, in case someone wants to express a preference.

**Comment by defeo** [comment]
Given a first shoot, using Lanyon. Mobile ready, does not work with IE <9.

Waiting for a logo and consortium identity.

**Comment by nthiery** [comment]
Thanks much!

I made some minor tweaks.

One question now that I have played a bit with it: having a folded away sidebar is nice and typical for mobiles. Elsewhere, I am wondering whether people won't overlook it; what about making it visible by default? Either by tweaking the style or switching to e.g. Hide?

Is it a standard thing of the themes to have news/index.html? Otherwise, for consistency with the other pages, we might want to have news/index.md if not just news.md.

**Comment by defeo** [comment]
It's easy to have the sidebar visible by default. We could also make it appear conditionnaly based on window width. If we keep the current organisation of content, I agree that it is best to have it on by default. If we put most of the content in the main page, then we can keep it hidden.

Haven't given much tought to `news/index.md` vs `news/index.html`, but the `news` folder is necessary beause of Jekyll's pagination system.

**Comment by nthiery** [comment]
On Wed, May 20, 2015 at 07:41:42AM -0700, Luca De Feo wrote:

>    It's easy to have the sidebar visible by default. We could also make it
>    appear conditionnaly based on window width. If we keep the current
>    organisation of content, I agree that it is best to have it on by
>    default. If we put most of the content in the main page, then we can
>    keep it hidden.

I like the way you organized the content. So let's keep it this way
and make the sidebar visible by default (or based on window width, as
you see fit). I'll look at the upcoming diff to learn how to do it
next time :-)

>    Haven't given much tought to news/index.md vs news/index.html,
>    but the news folder is necessary beause of Jekyll's pagination
>    system.

Ok, good to know.

Cheers,

##                 Nicolas

Nicolas M. Thiéry "Isil" nthiery@users.sf.net
http://Nicolas.Thiery.name/

**Comment by JohnCremona** [comment]
As soon as we have the correct information we need to have a more formal
statement about the funding, visible from every web page.

In the Job Openings page I think it is unwise to have "If you like
collaborative open source development, innovative technologies,
architectural challenges, autonomy, get in touch with us."  Apart from the
fact that we do not yet give readers any way to get in touch, I don't think
that we want to be swamped with emails from people most of whom are likely
to be unsuitable.  Each university will have its own procedures for making
appointments.  Any project-wide arrangements for recruitment should be
discussed by project leaders first.

Also "Loving math is a plus but not a necessity." is terrible.  Each post
will have its own job specifications.  And "math" is not English.  --End of
rant!

John

**Comment by nthiery** [comment]
On Wed, May 20, 2015 at 09:17:46AM -0700, John Cremona wrote:

>    As soon as we have the correct information we need to have a more
>    formal
>    statement about the funding, visible from every web page.

You mean referencing the European Commission, specific work program,
etc? Sounds reasonable indeed.

>    In the Job Openings page I think it is unwise to have "If you
>    like collaborative open source development, innovative
>    technologies, architectural challenges, autonomy, get in touch
>    with us." Apart from the fact that we do not yet give readers any
>    way to get in touch, I don't think that we want to be swamped
>    with emails from people most of whom are likely to be
>    unsuitable. Each university will have its own procedures for
>    making appointments. Any project-wide arrangements for
>    recruitment should be discussed by project leaders first.  Also
>    "Loving math is a plus but not a necessity." is terrible. Each
>    post will have its own job specifications. And "math" is not
>    English. --End of rant!

Ok. Please go ahead and edit as you see fit.

Cheers,

##                 Nicolas

Nicolas M. Thiéry "Isil" nthiery@users.sf.net
http://Nicolas.Thiery.name/

**Comment by defeo** [comment]
I spoke too fast. Having the menu open by default in Lanyon wouldn't look nice for most window sizes. To see it, open the drawer and resize your browser window: the text gets cropped on the left for most sizes.

If we want an always on menu, we can either go with Hyde, or roll our own menu (e.g., a top navbar) on top of Poole. I'll give both a try and post examples here.

**Comment by nthiery** [comment]
On Wed, May 20, 2015 at 04:42:01PM -0700, Luca De Feo wrote:

>    I spoke too fast. Having the menu open by default in Lanyon wouldn't
>    look nice for most window sizes. To see it, open the drawer and resize
>    your browser window: the text gets cropped on the left for most sizes.

Ok, thanks for trying!

>    If we want an always on menu, we can either go with Hyde, or roll our
>    own menu (e.g., a top navbar) on top of Poole. I'll give both a try and
>    post examples here.

If Hyde works well on mobile, I'd say let's just stick to an existing
theme; but you know better :-)

Ah, by the way: at some point we probably want to choose some color
theme that somewhat matches that of the European portals.

```
    http://ec.europa.eu/research/participants/portal/
```

Maybe just having a blue background for the side bar. But that we can
do when we have a logo.

Cheers,

##                 Nicolas

Nicolas M. Thiéry "Isil" nthiery@users.sf.net
http://Nicolas.Thiery.name/

**Comment by JohnCremona** [comment]
On 20 May 2015 at 17:25, Nicolas M. Thiéry notifications@github.com wrote:

> On Wed, May 20, 2015 at 09:17:46AM -0700, John Cremona wrote:
> 
> > As soon as we have the correct information we need to have a more
> > formal
> > statement about the funding, visible from every web page.
> 
> You mean referencing the European Commission, specific work program,
> etc? Sounds reasonable indeed.

Yes, that is what I meant.

> > In the Job Openings page I think it is unwise to have "If you
> > like collaborative open source development, innovative
> > technologies, architectural challenges, autonomy, get in touch
> > with us." Apart from the fact that we do not yet give readers any
> > way to get in touch, I don't think that we want to be swamped
> > with emails from people most of whom are likely to be
> > unsuitable. Each university will have its own procedures for
> > making appointments. Any project-wide arrangements for
> > recruitment should be discussed by project leaders first. Also
> > "Loving math is a plus but not a necessity." is terrible. Each
> > post will have its own job specifications. And "math" is not
> > English. --End of rant!
> 
> Ok. Please go ahead and edit as you see fit.

Right, I will, but I wanted to air it here first.

John

**Comment by defeo** [comment]
Here's a shot at Hyde : http://defeo.lu/odk-hyde/. Do not mind about broken links and old content. Thoughts?

**Comment by nthiery** [comment]
On Thu, May 21, 2015 at 06:05:11PM -0700, Luca De Feo wrote:

>    Here's a shot at Hyde : [1]http://defeo.lu/odk-hyde/. Do not mind about
>    broken links and old content. Thoughts?

I have checked it with different sizes and on my cell phone. This
looks great to me; Thanks! Go ahead!

In case it's trivial: when the screen is small and the sidebar is made
into a topbar, Home / News/ ... could be put on a single line so save
some vertical space.

Cheers,

##                 Nicolas

Nicolas M. Thiéry "Isil" nthiery@users.sf.net
http://Nicolas.Thiery.name/

**Comment by defeo** [comment]
> I have checked it with different sizes and on my cell phone. This
> looks great to me; Thanks! Go ahead!

Ok. I'll roll it tonight.

The most reasonable way is rebasing the Lanyon site over this one, so
to avoid keeping Lanyon history in repo.

That would mean rewriting history, though. Objections ?

> In case it's trivial: when the screen is small and the sidebar is made
> into a topbar, Home / News/ ... could be put on a single line so save
> some vertical space.

I'll see what can be done.

**Comment by defeo** [comment]
There is the new Hyde theme, in a temporary branch:

https://github.com/OpenDreamKit/OpenDreamKit.github.io/tree/hyde

This branch is meant to **replace** the current `HEAD`. After we force-push this one onto `gh-pages`, everyone with a local copy should clone from scratch, rather than pull (which would give loads of conflicts).

Waiting for the green light.

**Comment by nthiery** [comment]
I am not sure slightly improving the history was worth the (small) trouble, but since it's done and I haven't commented in time, let's proceed! Thanks!

**Comment by defeo** [comment]
> I am not sure slightly improving the history was worth the (small) trouble,
> but since it's done and I haven't commented in time, let's proceed!

Hey, no big deal! It's just a matter of merging with `-s ours`.

I know rewriting history is bad, and I'll take even the slightest
objection as a no-go. I think keeping Hyde's history is important, so
that we can import updates in the projet, but erasing the Lanyon
history was just me being fascist.

I've merged the old Lanyon history in, and pushed. No need to
re-clone: history hasn't been rewritten, it's just a little bloated
now.

If at some point we do not like bloated history, we can still go back
and rewrite.

**Comment by nthiery** [comment]
On Sun, May 24, 2015 at 03:23:40PM -0700, Luca De Feo wrote:

>    Hey, no big deal!

Agreed: it indeed was a slightest hint :-)

Thanks a lot Luca, the site looks very nice!

Cheers,

##                 Nicolas

Nicolas M. Thiéry "Isil" nthiery@users.sf.net
http://Nicolas.Thiery.name/

**Comment by nchauvat** [comment]
On Sun, May 24, 2015 at 03:23:40PM -0700, Luca De Feo wrote:

> If at some point we do not like bloated history, we can still go back
> and rewrite.

... or switch to Mercurial and its obsolete changesets feature !

PS: sorry for the troll, I could not resist since obsolete changesets
and phases were started in Mercurial by Logilab folks. :p

## 

Nicolas Chauvat

logilab.fr - services en informatique scientifique et gestion de connaissances
