### ISSUE TITLE
Bordeaux, Kaiserslautern, Paris, Southampton, Simula job posting needs update

### ISSUE THREAD

**Issue by pdehaye** [OpenDreamKit/OpenDreamKit.github.io#30]
Either the job post contains reference to a 2015 deadline, or the start date is over. 

Start [here](https://github.com/OpenDreamKit/OpenDreamKit.github.io/blob/master/joinus.md) and also maybe update/copy/adapt the original post [here](https://github.com/OpenDreamKit/OpenDreamKit.github.io/tree/master/_posts).

This concerns Bordeaux, Kaiserslautern, Paris, Southampton, Simula.

**Comment by pdehaye** [comment]
(this is BTW the main concern of reviewers so far, and it is based on counting the number of job postings we have listed on the site)

**Comment by kohlhase** [comment]
You are right, and we should respond to it plausibly.

**Comment by pdehaye** [comment]
I was thinking that once those job postings are updated, we could try to identify EU and international conferences around the relevant tools (for instance Docker) and use the ODK Twitter account to tweet at relevant hashtags. What do you think @alex-konovalov ?

**Comment by minrk** [comment]
On the joinus page, the simula position is already listed as filled, as with some others. I updated the original post to indicate that the position has been filled as well. Is there more to do than that?

**Comment by nthiery** [comment]
On Wed, Jun 29, 2016 at 12:37:53AM -0700, Min RK wrote:

>    On the joinus page, the simula position is already listed as filled, as
>    with some others. I updated the original post to indicate that the
>    position has been filled as well. Is there more to do than that?

All good. Thanks!

##                 Nicolas

Nicolas M. Thiéry "Isil" nthiery@users.sf.net
http://Nicolas.Thiery.name/
