### ISSUE TITLE
Jeroen's ipywidgets slides from ICMS 2017

### ISSUE THREAD

**Issue by willfurnass** [OpenDreamKit/OpenDreamKit.github.io#52]
@jdemeyer Would you be able to add copies of / a link to your slides to the [ICMS 2017 programme](meetings/2017-01-16-ICMS/programme.md)?

**Comment by jdemeyer** [comment]
Done, see http://opendreamkit.github.io/meetings/2017-01-16-ICMS/talks/IPywidgets%20Demeyer.ipynb
