### ISSUE TITLE
Fix and reinstate continuous integration for our web site

### ISSUE THREAD

**Issue by nthiery** [OpenDreamKit/OpenDreamKit.github.io#69]
Someone (@defeo?) had set up continuous integration with Travis for our web site. That's certainly a good thing to have. Nevertheless, it has recently systematically failed with an error that looks like a config error, and this is just confusing to our contributors. I had a brief look, but am not familiar enough with Travis/ruby/... to fix this promptly myself. I therefore temporarilly [disabled Travis](https://travis-ci.org/OpenDreamKit/OpenDreamKit.github.io/settings) for now.

Please anyone, fix and reinstate!

cc @kohlhase, @embray

**Comment by kohlhase** [comment]
I thought @VivianePons fixed it last time.

**Comment by kohlhase** [comment]
You should be aware that until Travis is reinstated, the ODK web site will not be updated with commits. In particular, the site reports that are still coming in will not be visible.

**Comment by nthiery** [comment]
> You should be aware that until Travis is reinstated, the ODK web
> site will not be updated with commits. In particular, the site
> reports that are still coming in will not be visible.

You made me doubt :-) But I just double checked. The website update is
taken care off by github itself. No Travis involved. On the other
hand, github's feedback tends to be very poor when it fails to update
the site. So there are certainly cases where Travis would be helpful
to debug why github is not updating the site.

**Comment by defeo** [comment]
Well, this is weird. Travis has **never** worked, simply because there is no `.travis.yml` file in the repo!

I wonder who activated Travis. a lot of clues point to... me :) I even have a never-commited `.travis.yml` in my local repo, but I recall nothing of it! I must have been trying to set it up, and then forgotten about it.

Sorry, about that. I'm going to fix it, it may generate some noise in the next few commits.

**Comment by nthiery** [comment]
> a lot of clues point to... me :)

:-)

That was a good action to start!

> I'm going to fix it

Thanks!

**Comment by defeo** [comment]
Done.

Travis now checks for broken links, so we will have to be careful about those if we do not want it to fail again.

**Comment by nthiery** [comment]
>    Travis now checks for broken links, so we will have to be careful about
>    those if we do not want it to fail again.

Great; as long as we get a clear report about them, that's exactly
what we want. Thank you Luca for setting up CI for us!
