### ISSUE TITLE
Two almost identical paragraphs in the news

### ISSUE THREAD

**Issue by olexandr-konovalov** [OpenDreamKit/OpenDreamKit.github.io#7]
http://opendreamkit.org/news/ has two items:
- http://opendreamkit.org/2015/01/15/proposal-submitted/ (Jan 15th)
- http://opendreamkit.org/2015/01/31/open-proposal-writing/ (Jan 31st)

the shortened versions of which look almost identical. Only opening them reveals that actually the more recent one is much more longer.

**Comment by nthiery** [comment]
On Mon, May 25, 2015 at 05:30:27AM -0700, Alexander Konovalov wrote:

>    [1]http://opendreamkit.org/news/ has two items:
>      \* [2]http://opendreamkit.org/2015/01/15/proposal-submitted/ (Jan
>        15th)
>      \* [3]http://opendreamkit.org/2015/01/31/open-proposal-writing/ (Jan
>        31st)
> 
>    the shortened versions of which look almost identical. Only opening
>    them reveals that actually the more recent one is much more longer.

Indeed, now that the first paragraph of a blog post is used as short
version in the announcement, we have to make sure that it gives an
idea of the whole post. I added such a first paragraph to the second
one. If you think this does the job, please close this issue.

Cheers,

##                 Nicolas

Nicolas M. Thiéry "Isil" nthiery@users.sf.net
http://Nicolas.Thiery.name/

**Comment by defeo** [comment]
Can we close this issue?
