### ISSUE TITLE
Partner logos

### ISSUE THREAD

**Issue by defeo** [OpenDreamKit/OpenDreamKit.github.io#8]
We want to have a "Partners" page, with the logos of each partner involved, and links to the institution.

Please push your institution logo in https://github.com/OpenDreamKit/OpenDreamKit.github.io/tree/master/public/logos, or post a link in a comment in this issue. Please also post here the landing page your logo should point to.

Logos must be web-grade quality (~100KB), and adapted for inclusion on a white background.
- [X] Université Paris Sud: www.u-psud.fr

**Comment by JohnCremona** [comment]
For Warwick I have been supplied with these by the Warwick "marketing team".

http://homepages.warwick.ac.uk/staff/J.E.Cremona/UofW_CMYK_Colour_logo_+Descriptor.pdf
http://homepages.warwick.ac.uk/staff/J.E.Cremona/UofW_CMYK_Colour_logo_+Descriptor.eps

If by "landing page" you mean the university home page then it is here:

http://www2.warwick.ac.uk/

**Comment by fcayre** [comment]
For Logilab, please use:

https://www.logilab.fr/images/logilab.png
https://www.logilab.fr/images/logilab.svg

and point to: https://www.logilab.fr

**Comment by dimpase** [comment]
AFAIR, I pushed a logo long ago, as to the landing page, it is http://www.ox.ac.uk/

**Comment by martinal** [comment]
Min added the Simula logo, please point to https://www.simula.no/

**Comment by nthiery** [comment]
TODO: ping sites that haven't yet submitted a logo.

**Comment by fangohr** [comment]
Pushed a long time ago for Southampton to https://github.com/OpenDreamKit/OpenDreamKit.github.io/blob/master/public/logos/University-of-Southampton.pdf and https://github.com/OpenDreamKit/OpenDreamKit.github.io/blob/master/public/logos/University-of-Southampton.png

Institute link is http://www.southampton.ac.uk

**Comment by ClementPernet** [comment]
I pushed UJF's logo.
The url to point to is:
https://www.ujf-grenoble.fr

**Comment by pdehaye** [comment]
Pushed UZH Zurich's logo, url to point to: http://www.uzh.ch

**Comment by defeo** [comment]
Ok, so the partners/people page just landed http://opendreamkit.org/partners/ (maybe Shift+Ctrl+R to empty your stylesheet cache).

The naughty ODKids who did not send anything are:
- UKaiserlautern (someone ping Wolfram, please) @wbhart 
- USheffield @lawrennd 

The distracted ones who submitted a logo but did not give a URL to point to are:
- Jacobs Uni. Assuming http://www.jacobs-university.de/ @kohlhase 
- USilesia. Assuming http://english.us.edu.pl/ @marcinofulus 
- USTAN. Assuming https://www.st-andrews.ac.uk/ @stevelinton 

Make your modifications in the file https://github.com/OpenDreamKit/OpenDreamKit.github.io/blob/master/_data/partners.yml. I think the YAML format is self-explanatory. Do not forget to quote the URL (because of the semi-colon). Make a pull-request if in doubt.

I'm concerned about the CNRS/Bordeaux thing: which logo shall we use (you put both CNRS and LABRI)? Which name? Which link? For the moment I used LABRI (acronym expanded), because I felt CNRS is a trifle too generic, but I believe only @videlec is a member of it. I also put the CNRS logo at the bottom of the page.

**Comment by JohnCremona** [comment]
People could be encouraged to also add links to their own home pages from
their names?

John

**Comment by defeo** [comment]
This is [Issue 16](https://github.com/OpenDreamKit/OpenDreamKit.github.io/issues/16)

**Comment by nthiery** [comment]
Finished in 2e284bb4e995262b0ae8da94935db2f189d6dafe.
