### ISSUE TITLE
The European Comission (or h2020) logo should appear somewhere

### ISSUE THREAD

**Issue by videlec** [OpenDreamKit/OpenDreamKit.github.io#9]

**Comment by defeo** [comment]
https://ec.europa.eu/programmes/horizon2020/en/content/will-horizon-2020-have-logo-andor-visual-identity-which-easy-reproduce

though.

**Comment by videlec** [comment]
But the Europen Commission still has its logo. Doesn't it?

**Comment by defeo** [comment]
Well, they seem to say that they prefer having a verbal "Horizon 2020" (which we already have in the sidebar), eventually next to a generic european flag (which we may have if we like to):

> When Horizon 2020 is promoted by beneficiaries and other third parties, the European flag
> ([history and downloads](http://europa.eu/about-eu/basic-information/symbols/flag/index_en.htm)) can be used in conjunction with the words "Horizon 2020".

**Comment by nthiery** [comment]
On Fri, Jun 19, 2015 at 01:35:40AM -0700, Luca De Feo wrote:

>    Well, they seem to say that they prefer having a verbal "Horizon 2020"
>    (which we already have in the sidebar), eventually next to a generic
>    european flag (which we may have if we like to):

+1 to a european flag in the side bar!

Cheers,
                Nicolas

**Comment by nthiery** [comment]
I added a EU flag.

It would be better to make its width proportional to the width of the
OpenDreamKit text to better render on small screens (e.g. mobile). Or
simply remove the EU flag on such screens.

By the way: if someone knows how to put the text in the sidebar ragged
to the top rather than the bottom it feels like this would be more
natural.

**Comment by nthiery** [comment]
Shall we close that issue?

**Comment by bpilorget** [comment]
I guess so.

**Comment by bpilorget** [comment]
We must keep in mind we will need to keep the EU flag when the logo is done.
