### ISSUE TITLE
Make a default image for posts in the web page. 

### ISSUE THREAD

**Issue by kohlhase** [OpenDreamKit/OpenDreamKit.github.io#94]
The grid layout of the posts is nice, but only when there are images (see also #93). So we should have a default picture (I am thinking the OpenDreamKit Logo) for those posts that do not provide one. 

I am assigning that to Luca and Viviane, since they seemed to involved in the web site programming.

**Comment by nthiery** [comment]
On Thu, Nov 01, 2018 at 12:18:19AM -0700, Michael Kohlhase wrote:
>    The grid layout of the posts is nice, but only when there are images
>    (see also [1]#93). So we should have a default picture (I am thinking
>    the OpenDreamKit Logo) for those posts that do not provide one.

That, or raging down the text by any other mean. Could be a
transparent image too.

**Comment by nthiery** [comment]
Done by inserting a vertical space filler: 758aec3868e3b18e4ea8e2d890791af49f5b9d44 .

**Comment by nthiery** [comment]
Btw: @kohlhase: the image for the VR post being in a vertical format, does not render so well with the other images that are more of a 4/3 ratio. Could we adapt it?

**Comment by kohlhase** [comment]
done.
